<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net35;net8.0</TargetFrameworks>
    <AssemblyName>CSM.Forge.Protocol</AssemblyName>
    <RootNamespace>CsmForge.Protocol</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Forge.Core/Forge.Core.csproj" />
  </ItemGroup>
</Project>
